### ISSUE TITLE
Not working for multiplayer

### ISSUE THREAD

**Issue by DJLegends1011** [Globox1997/Nameplate#1]
Works fine for singleplayer but its stuck on lvl 1 even though RPG mod has mapped up entities to lvl 20

**Comment by DJLegends1011** [comment]
basically, hadn't had it enabled when I made the server hours later I just found this addon and difficulty was already doing its work but everyone was still on LVL 1 when I make a single-player map it works fine see a couple of lvl 5 etc

**Comment by Globox1997** [comment]
Yea the mod has to get installed on the server too otherwise it doesn't work
