### ISSUE TITLE
Crash on Startup at 1.19.2

### ISSUE THREAD

**Issue by Rivmun** [Globox1997/Nameplate#10]
Hi, I've got a problem about Nameplate. When I startup my modpacks after installed Nameplate, NotEnoughCrash mod will show a crash screen for me. Here is crash report (and modlist):
[crash-2022-09-21_16.01.11-server.txt](https://github.com/Globox1997/Nameplate/files/9614719/crash-2022-09-21_16.01.11-server.txt)
Startup successfully after Nameplate removed.

**Comment by Globox1997** [comment]
Thanks for reporting, had mapping issues, fixed with [https://github.com/Globox1997/Nameplate/commit/1a70eae263814ffa7c8a5a2ac3a26adcd1c23a48](https://github.com/Globox1997/Nameplate/commit/1a70eae263814ffa7c8a5a2ac3a26adcd1c23a48)
