### ISSUE TITLE
1.18.2 JSON5 file still resetting

### ISSUE THREAD

**Issue by Elska85** [Globox1997/Nameplate#11]
json5 config file resetting every launch 

I know we commented before how the issue was resolved, but if that change could happen with the 1.18.2 version that would be great. I saved a copy as a JSON file to see if that would work and hope Minecraft would prioritize it but this does not seem to be the case.

**Comment by Globox1997** [comment]
Yes this is a known issue for older versions cause of json5 usage instead of json.
Out of time reasons I only work on the latest version tho

**Comment by Elska85** [comment]
Ok I guess I won't be using this mod then. Thanks for getting back to me.

**Comment by Globox1997** [comment]
Then this can get closed I guess
