### ISSUE TITLE
Incompatibility with 'The Graveyard (Fabric)' Mod

### ISSUE THREAD

**Issue by Kalahatze** [Globox1997/Nameplate#12]
Minecraft freezes and gets stuck during launch when using Nameplate mod with The Graveyard (Fabric).

[latest.log](https://github.com/Globox1997/Nameplate/files/9714619/latest.log)

**Comment by guitarist4hire** [comment]
having the EXACT same issue!

**Comment by Globox1997** [comment]
Thanks for report, fixed with [https://github.com/Globox1997/Nameplate/commit/ffad4bca505b0a61ff2455ac5ad7db0b10a9cf86](https://github.com/Globox1997/Nameplate/commit/ffad4bca505b0a61ff2455ac5ad7db0b10a9cf86)
