### ISSUE TITLE
Modded Mobs have double nametags

### ISSUE THREAD

**Issue by PixelatedBruh** [Globox1997/Nameplate#14]
If you rename any mob from a mod with a name tag. It will cause another name tag to spawn when you look at the mob. Im guessing that's that vanilla tag showing up. I noticed when naming vanilla mobs that this does not happen. in addition mobs that add names to the mobs (Eldritch mobs for example) cause the double name tag as well. I had to disable the titles in that mod to stop it. but there is no way to do that for nametags

one showing a mods mob

and a vanilla one (the pig is vanilla it just looks different do to a mod)
![2022-10-23_03 44 03](https://user-images.githubusercontent.com/54760551/197387676-ce5c1481-3b0e-4008-a834-445d9722e49b.png)
![2022-10-23_03 44 49](https://user-images.githubusercontent.com/54760551/197387702-25108a00-ca09-43d0-9b10-eedc7b96f00a.png)

**Comment by Globox1997** [comment]
[nameplate-1.0.10.zip](https://github.com/Globox1997/Nameplate/files/9919372/nameplate-1.0.10.zip)
Does this fix the issue?

**Comment by thrasos-dev** [comment]
> [nameplate-1.0.10.zip](https://github.com/Globox1997/Nameplate/files/9919372/nameplate-1.0.10.zip)
> Does this fix the issue?

I have tried using the updated 1.0.10 version you have provided, but the problem persists
<img width="1552" alt="Screenshot 2022-11-04 at 20 46 41" src="https://user-images.githubusercontent.com/100732009/200062376-af6b6ce6-5c2a-4b92-9023-05b3f7975d8c.png">

**Comment by Globox1997** [comment]
This is pretty sure fixed with the latest update, reopen if still exist
