### ISSUE TITLE
Nameplate does not accurately show levels for structure spawned mobs/spawner mobs

### ISSUE THREAD

**Issue by GooopenWasntAvailable** [Globox1997/Nameplate#16]
![image](https://user-images.githubusercontent.com/81867354/218313793-1e2cfcd0-62a8-412c-904a-3411d939a24e.png)

**Comment by GooopenWasntAvailable** [comment]
I am using Nameplate-1.0.10 for 1.19.2.

**Comment by Globox1997** [comment]
Thanks for reporting, fixed with [https://github.com/Globox1997/Nameplate/commit/d8a52e02e1a56ceca59801937408fa0e33e4029f](https://github.com/Globox1997/Nameplate/commit/d8a52e02e1a56ceca59801937408fa0e33e4029f)
