### ISSUE TITLE
More Configurability!

### ISSUE THREAD

**Issue by pokesmells** [Globox1997/Nameplate#17]
Currently you are only allow to hide/show the name and level, and the way color is formatted is a bit odd.

A user might not understand what -1 or the large color code utilized in the config means.
![image](https://user-images.githubusercontent.com/33227568/223572202-4b640c67-f60d-46d0-bf58-576c0109db94.png)

**A few improvements would be:**

Using HEX/RGB color codes to make it much easier to select colors for the nameplate.

Being able to change the size of the name plate it self.

Changing the X or Y positions of the nameplate so it can sit well with other mods that could conflict and it's just a nice to have.

Implementing a heath bar feature, this is merely a nice add-on, but it wouldn't be hard to do, and it would be just overall a nice feature and this could be toggleable, something similar to YDM's heath bar mod.

**Comment by Globox1997** [comment]
Hey Poke, thanks for the suggestions.
The color can already be changed with HEX code, just have to be set in the correct vanilla way.
It is done like this 0xAARRGGBB.
Added size and y pos settings with [https://github.com/Globox1997/Nameplate/commit/d8a52e02e1a56ceca59801937408fa0e33e4029f](https://github.com/Globox1997/Nameplate/commit/d8a52e02e1a56ceca59801937408fa0e33e4029f).
I have currently no health bar feature in mind, mainly cause there are other mods like you said which already do that.
Nameplate has WTHIT support btw.

**Comment by SooarynAC** [comment]
> Hey Poke, thanks for the suggestions. The color can already be changed with HEX code, just have to be set in the correct vanilla way. It is done like this 0xAARRGGBB. Added size and y pos settings with [d8a52e0](https://github.com/Globox1997/Nameplate/commit/d8a52e02e1a56ceca59801937408fa0e33e4029f). I have currently no health bar feature in mind, mainly cause there are other mods like you said which already do that. Nameplate has WTHIT support btw.

Adding Jade support as well would be nice

**Comment by Globox1997** [comment]
Added jade support with [https://github.com/Globox1997/Nameplate/commit/da4d90ac9c6f41f824a932a7ee58c0c3ca442f1b](https://github.com/Globox1997/Nameplate/commit/da4d90ac9c6f41f824a932a7ee58c0c3ca442f1b)

**Comment by Globox1997** [comment]
Added a healthbar feature, I guess that is all.
