### ISSUE TITLE
No config settings work on server

### ISSUE THREAD

**Issue by PixelatedBruh** [Globox1997/Nameplate#19]
With level z and nameplate installed client and server same settings. on single player the multiplier works and is showing the correct intended level. while on the server it shows the incorrect level (by half) I set the level multiplier to 20 on both  and with my settings it should show level 100
but it only shows level 100 in single player
and level 50 in the server 
(only config changed in nameplate is the level multiplier from 10 to 20)
I believe the level multiplier config in nameplate does not change it on the server

**Comment by PixelatedBruh** [comment]
I was able to solve my problem by changing the default value from 10 to 20 in the config java file then compiling the mod. It appears that changes to the config are the only issue as it functions correctly after this

**Comment by PixelatedBruh** [comment]
I would like to say NO setting in the config works for the server setting

**Comment by muon-rw** [comment]
The config file likely needs to be regenerated before editing. I had the same issue and got it work by deleting the file, restarting the server, then making changes.

**Comment by Globox1997** [comment]
The config setting works as intended, you have to set the config on the server (as you did) and reload the server + maybe kill all existing mobs (not sure about that)
if this is still an issue for ya, come to my discord.
