### ISSUE TITLE
Config option for how level is calculated, separate from load conditions

### ISSUE THREAD

**Issue by muon-rw** [Globox1997/Nameplate#21]
### Make sure you are not opening a duplicate.

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

Currently Nameplate checks for RPGDifficulty and if it’s installed, displays those instead of calculating the level based on max health change.

The issue with this is that I’d like to use multiple difficulty scaling mods together (rpgdifficulty, dungeon difficulty, and Eldritch mobs), and although Nameplate properly scales the level for DD and Eldritch normally, when RPGdifficulty is installed, powerful mobs modified by these other difficulty mods still display as level 1.

I think either of these would work well:
1. Config option for “use RPGDifficulty Level” instead of forcing it when the mod is installed
2. Change RPGDifficulty level to an entity attribute so it can be scaled by other mods (but option 1 alone would be enough)

**Comment by Globox1997** [comment]
Sounds like a good solution, added a config option with [https://github.com/Globox1997/Nameplate/commit/79d3619027788c5305362c7f04daf929e6ec3fcd](https://github.com/Globox1997/Nameplate/commit/79d3619027788c5305362c7f04daf929e6ec3fcd)
