### ISSUE TITLE
Traveler's Title difficulty integration only works if RPGDifficulty is loaded

### ISSUE THREAD

**Issue by muon-rw** [Globox1997/Nameplate#22]
### Minecraft Version

1.19.x

### Mod Loader Version

0.14.21

### Mod Version

1.1.3+1.19.2

### Describe the Issue

To reproduce:
1. Install Nameplate and Dungeon Difficulty, but not RPG Difficulty 
2. Scale mobs for a biome or dimension's difficulty with Dungeon Difficulty (including Skeletons)
3. Mob level no longer displays on Traveler's Titles, even though it displays properly on mobs.

![image](https://github.com/Globox1997/Nameplate/assets/128171313/46bc6c77-c00c-4df2-b99e-71cbe501cea9)
![image](https://github.com/Globox1997/Nameplate/assets/128171313/5ce52c9a-9977-4936-8f91-128d2ed9d4ff)

### latest.log

https://mclo.gs/JK9XtX7

**Comment by Globox1997** [comment]
Thanks for reporting, fixed with [https://github.com/Globox1997/Nameplate/commit/16e211d483d13238040120e266bfe0c5bf447e23](https://github.com/Globox1997/Nameplate/commit/16e211d483d13238040120e266bfe0c5bf447e23)
