### ISSUE TITLE
Settings for Excluded Entities do not save

### ISSUE THREAD

**Issue by Prymz** [Globox1997/Nameplate#4]
The 'excluded entities' field in the settings does not retain changes between game restarts.
Changes made manually to the .json5 file in the config directory also are overridden.
(MC 1.19, FAPI 0.58, ClothAPI: 8.0.75, RPGDiff: 1.2.0 (Default Settings), Nameplate: 1.0.3 (Default Settings except the exclusions))

Additionally, it would be convenient if the 'excluded entities' lists were synced between RPGDifficulty and Nameplate.

**Comment by Elska85** [comment]
Been having this same issue, I even tried copying the script in the server config and it won't work.

**Comment by Samekichi** [comment]
- Same issue under Minecraft 1.18.2, FAPI 0.58.0, Cloth Config API 6.2.62, Fabric loader 0.14.8.
- Also a small question: Is there a way to add all mobs of a certain mod to the exclusion list (e.g., Earth2Java)?

**Comment by Globox1997** [comment]
Hope it is fixed with [https://github.com/Globox1997/Nameplate/commit/9a1a2fc021bfad856aba9cb22e5e113ab1ce9fbc](https://github.com/Globox1997/Nameplate/commit/9a1a2fc021bfad856aba9cb22e5e113ab1ce9fbc)

**Comment by Elska85** [comment]
> 
Is it updated on curse forge yet?
Looks like it was last updated in June. 
Also thanks for fixing this issue, I really appreciate your efforts mate.

**Comment by Globox1997** [comment]
No working on updates and want to upload them at one time
Hopefully tomorrow I'm finished

**Comment by Globox1997** [comment]
Fixed with the latest update, using json instead of json5 now
