### ISSUE TITLE
[Enhancement] Add options to disable nameplate on nonhostile mobs and mob name display

### ISSUE THREAD

**Issue by Samekichi** [Globox1997/Nameplate#6]
- An option to only display nameplate on hostile mobs would be great, cuz nameplates are usually not desirable in the circumstances of animal farms or pets. 
- For named mobs, the nameplate will overlap with Vanilla nametag displays.
- Though it may be weird to have **Name**plate not displaying mobs' names, adding an option to disable mob name display can make *Nameplate* more visually compatible with *Orderly*, a mob health bar mod.

**Comment by Globox1997** [comment]
Added hostile only config with [https://github.com/Globox1997/Nameplate/commit/9d13379cf7785eed974a2a3413e418f744f37de2](https://github.com/Globox1997/Nameplate/commit/9d13379cf7785eed974a2a3413e418f744f37de2)
The second one is at least with only this mod working
The third option already exists, check the config :)
