### ISSUE TITLE
Excluded Entities does not seem to work on multiplayer.

### ISSUE THREAD

**Issue by Coyote21** [Globox1997/Nameplate#7]
MC 1.18.2, Fabric API 0.58, Cloth-api: 3.2.64, RPGDiff: 1.0.12, Nameplate: 1.0.2

I can't seem to exclude any entities. I originally only wanted to exclude some passive mobs (Cows, Sheep, Pigs, etc) but when neither "minecraft:pig", nor "minecraft.pig", worked as entries in either the config screen or manually editing the config file I tried the provided example "minecraft.zombie" and that did not work either (I still get nameplates on Zombies).

**Comment by Globox1997** [comment]
Should be the same issue as [https://github.com/Globox1997/Nameplate/issues/4](https://github.com/Globox1997/Nameplate/issues/4)

**Comment by Coyote21** [comment]
I'm not sure how to incorporate that patch into my server? Do I just need to wait until you upload a new version to curseforge? I should I build it myself? (BTW, I don't really know how to do that).

**Comment by Globox1997** [comment]
Out of time reasons I only work on latest versions so this will be for 1.19.2

**Comment by Coyote21** [comment]
I understand, Just adds to the list of reasons to update to 1.19.2 myself.

Do you know of any obvious issues there may be if I ran the latest 1.19.2 version of Nameplate on a 1.18.2 server? (With the 1.18.2 version of RPGDifficulty)

I know some mods are backwards compatible. If it just needs a change to the mod.json file (or other txt file) I can do that.

**Comment by Globox1997** [comment]
Fixed with the latest update for 1.19.2
Not sure if it will work on older versions like 1.18.2 but not sure. The latest version isn't depending on rpgdifficulty anymore but maybe the other way around
